
package com.webservice.filesystem;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FileSystemService", targetNamespace = "http://filesystem.webservice.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FileSystemService {


    /**
     * 
     * @param pRuta
     * @param pCliente
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cambiarDirectorio", targetNamespace = "http://filesystem.webservice.com/", className = "com.webservice.filesystem.CambiarDirectorio")
    @ResponseWrapper(localName = "cambiarDirectorioResponse", targetNamespace = "http://filesystem.webservice.com/", className = "com.webservice.filesystem.CambiarDirectorioResponse")
    @Action(input = "http://filesystem.webservice.com/FileSystemService/cambiarDirectorioRequest", output = "http://filesystem.webservice.com/FileSystemService/cambiarDirectorioResponse")
    public String cambiarDirectorio(
        @WebParam(name = "pRuta", targetNamespace = "")
        String pRuta,
        @WebParam(name = "pCliente", targetNamespace = "")
        String pCliente);

    /**
     * 
     * @param pNombre
     * @param pCliente
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "encontrarElemento", targetNamespace = "http://filesystem.webservice.com/", className = "com.webservice.filesystem.EncontrarElemento")
    @ResponseWrapper(localName = "encontrarElementoResponse", targetNamespace = "http://filesystem.webservice.com/", className = "com.webservice.filesystem.EncontrarElementoResponse")
    @Action(input = "http://filesystem.webservice.com/FileSystemService/encontrarElementoRequest", output = "http://filesystem.webservice.com/FileSystemService/encontrarElementoResponse")
    public String encontrarElemento(
        @WebParam(name = "pNombre", targetNamespace = "")
        String pNombre,
        @WebParam(name = "pCliente", targetNamespace = "")
        String pCliente);

    /**
     * 
     * @param pTamano
     * @param pSectores
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "crearDisco", targetNamespace = "http://filesystem.webservice.com/", className = "com.webservice.filesystem.CrearDisco")
    @ResponseWrapper(localName = "crearDiscoResponse", targetNamespace = "http://filesystem.webservice.com/", className = "com.webservice.filesystem.CrearDiscoResponse")
    @Action(input = "http://filesystem.webservice.com/FileSystemService/crearDiscoRequest", output = "http://filesystem.webservice.com/FileSystemService/crearDiscoResponse")
    public String crearDisco(
        @WebParam(name = "pSectores", targetNamespace = "")
        int pSectores,
        @WebParam(name = "pTamano", targetNamespace = "")
        int pTamano);

    /**
     * 
     * @param pContenido
     * @param pNombre
     * @param pCliente
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "crearArchivo", targetNamespace = "http://filesystem.webservice.com/", className = "com.webservice.filesystem.CrearArchivo")
    @ResponseWrapper(localName = "crearArchivoResponse", targetNamespace = "http://filesystem.webservice.com/", className = "com.webservice.filesystem.CrearArchivoResponse")
    @Action(input = "http://filesystem.webservice.com/FileSystemService/crearArchivoRequest", output = "http://filesystem.webservice.com/FileSystemService/crearArchivoResponse")
    public String crearArchivo(
        @WebParam(name = "pNombre", targetNamespace = "")
        String pNombre,
        @WebParam(name = "pContenido", targetNamespace = "")
        String pContenido,
        @WebParam(name = "pCliente", targetNamespace = "")
        String pCliente);

    /**
     * 
     * @param pNombre
     * @param pCliente
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "crearDirectorio", targetNamespace = "http://filesystem.webservice.com/", className = "com.webservice.filesystem.CrearDirectorio")
    @ResponseWrapper(localName = "crearDirectorioResponse", targetNamespace = "http://filesystem.webservice.com/", className = "com.webservice.filesystem.CrearDirectorioResponse")
    @Action(input = "http://filesystem.webservice.com/FileSystemService/crearDirectorioRequest", output = "http://filesystem.webservice.com/FileSystemService/crearDirectorioResponse")
    public String crearDirectorio(
        @WebParam(name = "pNombre", targetNamespace = "")
        String pNombre,
        @WebParam(name = "pCliente", targetNamespace = "")
        String pCliente);

    /**
     * 
     * @param pCliente
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarDirectorio", targetNamespace = "http://filesystem.webservice.com/", className = "com.webservice.filesystem.ListarDirectorio")
    @ResponseWrapper(localName = "listarDirectorioResponse", targetNamespace = "http://filesystem.webservice.com/", className = "com.webservice.filesystem.ListarDirectorioResponse")
    @Action(input = "http://filesystem.webservice.com/FileSystemService/listarDirectorioRequest", output = "http://filesystem.webservice.com/FileSystemService/listarDirectorioResponse")
    public String listarDirectorio(
        @WebParam(name = "pCliente", targetNamespace = "")
        String pCliente);

    /**
     * 
     * @param pContenido
     * @param pNombre
     * @param pCliente
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modificarArchivo", targetNamespace = "http://filesystem.webservice.com/", className = "com.webservice.filesystem.ModificarArchivo")
    @ResponseWrapper(localName = "modificarArchivoResponse", targetNamespace = "http://filesystem.webservice.com/", className = "com.webservice.filesystem.ModificarArchivoResponse")
    @Action(input = "http://filesystem.webservice.com/FileSystemService/modificarArchivoRequest", output = "http://filesystem.webservice.com/FileSystemService/modificarArchivoResponse")
    public String modificarArchivo(
        @WebParam(name = "pNombre", targetNamespace = "")
        String pNombre,
        @WebParam(name = "pContenido", targetNamespace = "")
        String pContenido,
        @WebParam(name = "pCliente", targetNamespace = "")
        String pCliente);

    /**
     * 
     * @param pNombre
     * @param pCliente
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verPropiedades", targetNamespace = "http://filesystem.webservice.com/", className = "com.webservice.filesystem.VerPropiedades")
    @ResponseWrapper(localName = "verPropiedadesResponse", targetNamespace = "http://filesystem.webservice.com/", className = "com.webservice.filesystem.VerPropiedadesResponse")
    @Action(input = "http://filesystem.webservice.com/FileSystemService/verPropiedadesRequest", output = "http://filesystem.webservice.com/FileSystemService/verPropiedadesResponse")
    public String verPropiedades(
        @WebParam(name = "pNombre", targetNamespace = "")
        String pNombre,
        @WebParam(name = "pCliente", targetNamespace = "")
        String pCliente);

    /**
     * 
     * @param pNombre
     * @param pCliente
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "contenidoArchivo", targetNamespace = "http://filesystem.webservice.com/", className = "com.webservice.filesystem.ContenidoArchivo")
    @ResponseWrapper(localName = "contenidoArchivoResponse", targetNamespace = "http://filesystem.webservice.com/", className = "com.webservice.filesystem.ContenidoArchivoResponse")
    @Action(input = "http://filesystem.webservice.com/FileSystemService/contenidoArchivoRequest", output = "http://filesystem.webservice.com/FileSystemService/contenidoArchivoResponse")
    public String contenidoArchivo(
        @WebParam(name = "pNombre", targetNamespace = "")
        String pNombre,
        @WebParam(name = "pCliente", targetNamespace = "")
        String pCliente);

    /**
     * 
     * @param pRutaDestino
     * @param pNombre
     * @param pCliente
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "copiarElemento", targetNamespace = "http://filesystem.webservice.com/", className = "com.webservice.filesystem.CopiarElemento")
    @ResponseWrapper(localName = "copiarElementoResponse", targetNamespace = "http://filesystem.webservice.com/", className = "com.webservice.filesystem.CopiarElementoResponse")
    @Action(input = "http://filesystem.webservice.com/FileSystemService/copiarElementoRequest", output = "http://filesystem.webservice.com/FileSystemService/copiarElementoResponse")
    public String copiarElemento(
        @WebParam(name = "pNombre", targetNamespace = "")
        String pNombre,
        @WebParam(name = "pRutaDestino", targetNamespace = "")
        String pRutaDestino,
        @WebParam(name = "pCliente", targetNamespace = "")
        String pCliente);

    /**
     * 
     * @param pRutaDestino
     * @param pNombre
     * @param pCliente
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "moverElemento", targetNamespace = "http://filesystem.webservice.com/", className = "com.webservice.filesystem.MoverElemento")
    @ResponseWrapper(localName = "moverElementoResponse", targetNamespace = "http://filesystem.webservice.com/", className = "com.webservice.filesystem.MoverElementoResponse")
    @Action(input = "http://filesystem.webservice.com/FileSystemService/moverElementoRequest", output = "http://filesystem.webservice.com/FileSystemService/moverElementoResponse")
    public String moverElemento(
        @WebParam(name = "pNombre", targetNamespace = "")
        String pNombre,
        @WebParam(name = "pRutaDestino", targetNamespace = "")
        String pRutaDestino,
        @WebParam(name = "pCliente", targetNamespace = "")
        String pCliente);

    /**
     * 
     * @param pNombre
     * @param pCliente
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removerElemento", targetNamespace = "http://filesystem.webservice.com/", className = "com.webservice.filesystem.RemoverElemento")
    @ResponseWrapper(localName = "removerElementoResponse", targetNamespace = "http://filesystem.webservice.com/", className = "com.webservice.filesystem.RemoverElementoResponse")
    @Action(input = "http://filesystem.webservice.com/FileSystemService/removerElementoRequest", output = "http://filesystem.webservice.com/FileSystemService/removerElementoResponse")
    public String removerElemento(
        @WebParam(name = "pNombre", targetNamespace = "")
        String pNombre,
        @WebParam(name = "pCliente", targetNamespace = "")
        String pCliente);

    /**
     * 
     * @param pCliente
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generarArbol", targetNamespace = "http://filesystem.webservice.com/", className = "com.webservice.filesystem.GenerarArbol")
    @ResponseWrapper(localName = "generarArbolResponse", targetNamespace = "http://filesystem.webservice.com/", className = "com.webservice.filesystem.GenerarArbolResponse")
    @Action(input = "http://filesystem.webservice.com/FileSystemService/generarArbolRequest", output = "http://filesystem.webservice.com/FileSystemService/generarArbolResponse")
    public String generarArbol(
        @WebParam(name = "pCliente", targetNamespace = "")
        String pCliente);

    /**
     * 
     * @param pCliente
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerRuta", targetNamespace = "http://filesystem.webservice.com/", className = "com.webservice.filesystem.ObtenerRuta")
    @ResponseWrapper(localName = "obtenerRutaResponse", targetNamespace = "http://filesystem.webservice.com/", className = "com.webservice.filesystem.ObtenerRutaResponse")
    @Action(input = "http://filesystem.webservice.com/FileSystemService/obtenerRutaRequest", output = "http://filesystem.webservice.com/FileSystemService/obtenerRutaResponse")
    public String obtenerRuta(
        @WebParam(name = "pCliente", targetNamespace = "")
        String pCliente);

}
