
package com.webservice.filesystem;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FileSystemServiceService", targetNamespace = "http://filesystem.webservice.com/", wsdlLocation = "http://localhost:8080/ServidorFileSystem/FileSystemServiceService?WSDL")
public class FileSystemServiceService
    extends Service
{

    private final static URL FILESYSTEMSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException FILESYSTEMSERVICESERVICE_EXCEPTION;
    private final static QName FILESYSTEMSERVICESERVICE_QNAME = new QName("http://filesystem.webservice.com/", "FileSystemServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ServidorFileSystem/FileSystemServiceService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FILESYSTEMSERVICESERVICE_WSDL_LOCATION = url;
        FILESYSTEMSERVICESERVICE_EXCEPTION = e;
    }

    public FileSystemServiceService() {
        super(__getWsdlLocation(), FILESYSTEMSERVICESERVICE_QNAME);
    }

    public FileSystemServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FILESYSTEMSERVICESERVICE_QNAME, features);
    }

    public FileSystemServiceService(URL wsdlLocation) {
        super(wsdlLocation, FILESYSTEMSERVICESERVICE_QNAME);
    }

    public FileSystemServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FILESYSTEMSERVICESERVICE_QNAME, features);
    }

    public FileSystemServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileSystemServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FileSystemService
     */
    @WebEndpoint(name = "FileSystemServicePort")
    public FileSystemService getFileSystemServicePort() {
        return super.getPort(new QName("http://filesystem.webservice.com/", "FileSystemServicePort"), FileSystemService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FileSystemService
     */
    @WebEndpoint(name = "FileSystemServicePort")
    public FileSystemService getFileSystemServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://filesystem.webservice.com/", "FileSystemServicePort"), FileSystemService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FILESYSTEMSERVICESERVICE_EXCEPTION!= null) {
            throw FILESYSTEMSERVICESERVICE_EXCEPTION;
        }
        return FILESYSTEMSERVICESERVICE_WSDL_LOCATION;
    }

}
